name: Build delta-kernel-rust-sharing-wrapper wheels for 4 OS and 2 architectures

on:
  push:
    paths:
      - python/delta-kernel-rust-sharing-wrapper/**
      - .github/workflows/**
  pull_request:
    paths:
      - python/delta-kernel-rust-sharing-wrapper/**
      - .github/workflows/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, macos-latest, windows-latest]
        python-version: [3.8]
        arch: [x86_64, arm64]
        exclude:
          - os: ubuntu-latest
            arch: arm64
          - os: ubuntu-24.04
            arch: arm64
          - os: ubuntu-22.04
            arch: arm64
          - os: windows-latest
            arch: arm64

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install maturin
        run: pip install maturin

      - name: Build wheel (x86_64 macOS)
        if: matrix.os == 'macos-latest' && matrix.arch == 'x86_64'
        run: |
          rustup target add x86_64-apple-darwin
          cd python/delta-kernel-rust-sharing-wrapper
          maturin build --release --target x86_64-apple-darwin
        shell: bash

      - name: Build wheel (ARM macOS)
        if: matrix.os == 'macos-latest' && matrix.arch == 'arm64'
        run: |
          rustup target add aarch64-apple-darwin
          cd python/delta-kernel-rust-sharing-wrapper
          maturin build --release --target aarch64-apple-darwin
        shell: bash

      - name: Build wheel (x86_64 Windows)
        if: runner.os == 'Windows'
        run: |
          cd python/delta-kernel-rust-sharing-wrapper
          maturin build --release
        shell: powershell

      - name: Build wheel (x86_64 Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd python/delta-kernel-rust-sharing-wrapper
          maturin build --release
        shell: bash

      - name: Build wheel (x86_64 Linux Ubuntu 24.04)
        if: matrix.os == 'ubuntu-24.04'
        run: |
          cd python/delta-kernel-rust-sharing-wrapper
          maturin build --release
        shell: bash

      - name: Build wheel (x86_64 Linux Ubuntu 22.04)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          cd python/delta-kernel-rust-sharing-wrapper
          maturin build --release
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}-${{ matrix.arch }}
          path: python/delta-kernel-rust-sharing-wrapper/target/wheels/*.whl

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: all-wheels
          pattern: wheel-*
